#include "Glfw.h"
#ifdef GLVF_PLATFORM_GLFW
GLVFKey _glvfKeyCast(int key)
{
    switch (key)
    {
        case GLFW_KEY_SPACE:
            return GLVF_KEY_SPACE;
        case GLFW_KEY_APOSTROPHE:
            return GLVF_KEY_UNKNOWN; // TODO apostrophe
        case GLFW_KEY_COMMA:
            return GLVF_KEY_COMMA;
        case GLFW_KEY_MINUS:
            return GLVF_KEY_MINUS;
        case GLFW_KEY_PERIOD:
            return GLVF_KEY_PERIOD;
        case GLFW_KEY_SLASH:
            return GLVF_KEY_SLASH;
        case GLFW_KEY_0:
            return GLVF_KEY_NUMBER0;
        case GLFW_KEY_1:
            return GLVF_KEY_NUMBER1;
        case GLFW_KEY_2:
            return GLVF_KEY_NUMBER2;
        case GLFW_KEY_3:
            return GLVF_KEY_NUMBER3;
        case GLFW_KEY_4:
            return GLVF_KEY_NUMBER4;
        case GLFW_KEY_5:
            return GLVF_KEY_NUMBER5;
        case GLFW_KEY_6:
            return GLVF_KEY_NUMBER6;
        case GLFW_KEY_7:
            return GLVF_KEY_NUMBER7;
        case GLFW_KEY_8:
            return GLVF_KEY_NUMBER8;
        case GLFW_KEY_9:
            return GLVF_KEY_NUMBER9;
        case GLFW_KEY_SEMICOLON:
            return GLVF_KEY_SEMICOLON;
        case GLFW_KEY_EQUAL:
            return GLVF_KEY_UNKNOWN; // TODO equal
        case GLFW_KEY_A:
            return GLVF_KEY_A;
        case GLFW_KEY_B:
            return GLVF_KEY_B;
        case GLFW_KEY_C:
            return GLVF_KEY_C;
        case GLFW_KEY_D:
            return GLVF_KEY_D;
        case GLFW_KEY_E:
            return GLVF_KEY_E;
        case GLFW_KEY_F:
            return GLVF_KEY_F;
        case GLFW_KEY_G:
            return GLVF_KEY_G;
        case GLFW_KEY_H:
            return GLVF_KEY_H;
        case GLFW_KEY_I:
            return GLVF_KEY_I;
        case GLFW_KEY_J:
            return GLVF_KEY_J;
        case GLFW_KEY_K:
            return GLVF_KEY_K;
        case GLFW_KEY_L:
            return GLVF_KEY_L;
        case GLFW_KEY_M:
            return GLVF_KEY_M;
        case GLFW_KEY_N:
            return GLVF_KEY_N;
        case GLFW_KEY_O:
            return GLVF_KEY_O;
        case GLFW_KEY_P:
            return GLVF_KEY_P;
        case GLFW_KEY_Q:
            return GLVF_KEY_Q;
        case GLFW_KEY_R:
            return GLVF_KEY_R;
        case GLFW_KEY_S:
            return GLVF_KEY_S;
        case GLFW_KEY_T:
            return GLVF_KEY_T;
        case GLFW_KEY_U:
            return GLVF_KEY_U;
        case GLFW_KEY_V:
            return GLVF_KEY_V;
        case GLFW_KEY_W:
            return GLVF_KEY_W;
        case GLFW_KEY_X:
            return GLVF_KEY_X;
        case GLFW_KEY_Y:
            return GLVF_KEY_Y;
        case GLFW_KEY_Z:
            return GLVF_KEY_Z;
        case GLFW_KEY_LEFT_BRACKET:
            return GLVF_KEY_L_BRACKET;
        case GLFW_KEY_BACKSLASH:
            return GLVF_KEY_BACKSLASH;
        case GLFW_KEY_RIGHT_BRACKET:
            return GLVF_KEY_R_BRACKET;
        case GLFW_KEY_GRAVE_ACCENT:
            return GLVF_KEY_GRAVE;
        case GLFW_KEY_WORLD_1:
        case GLFW_KEY_WORLD_2:
            return GLVF_KEY_UNKNOWN; // TODO world keys
        case GLFW_KEY_ESCAPE:
            return GLVF_KEY_ESCAPE;
        case GLFW_KEY_ENTER:
            return GLVF_KEY_ENTER;
        case GLFW_KEY_TAB:
            return GLVF_KEY_TAB;
        case GLFW_KEY_BACKSPACE:
            return GLVF_KEY_BACKSPACE;
        case GLFW_KEY_INSERT:
            return GLVF_KEY_INSERT;
        case GLFW_KEY_DELETE:
            return GLVF_KEY_DELETE;
        case GLFW_KEY_RIGHT:
            return GLVF_KEY_RIGHT;
        case GLFW_KEY_LEFT:
            return GLVF_KEY_LEFT;
        case GLFW_KEY_DOWN:
            return GLVF_KEY_DOWN;
        case GLFW_KEY_UP:
            return GLVF_KEY_UP;
        case GLFW_KEY_PAGE_UP:
            return GLVF_KEY_PAGE_UP;
        case GLFW_KEY_PAGE_DOWN:
            return GLVF_KEY_PAGE_DOWN;
        case GLFW_KEY_HOME:
            return GLVF_KEY_HOME;
        case GLFW_KEY_END:
            return GLVF_KEY_END;
        case GLFW_KEY_CAPS_LOCK:
            return GLVF_KEY_CAPS_LOCK;
        case GLFW_KEY_SCROLL_LOCK:
            return GLVF_KEY_SCROLL_LOCK;
        case GLFW_KEY_NUM_LOCK:
            return GLVF_KEY_NUM_LOCK;
        case GLFW_KEY_PRINT_SCREEN:
            return GLVF_KEY_PRINT_SCREEN;
        case GLFW_KEY_PAUSE:
            return GLVF_KEY_PAUSE;
        case GLFW_KEY_F1:
            return GLVF_KEY_F1;
        case GLFW_KEY_F2:
            return GLVF_KEY_F2;
        case GLFW_KEY_F3:
            return GLVF_KEY_F3;
        case GLFW_KEY_F4:
            return GLVF_KEY_F4;
        case GLFW_KEY_F5:
            return GLVF_KEY_F5;
        case GLFW_KEY_F6:
            return GLVF_KEY_F6;
        case GLFW_KEY_F7:
            return GLVF_KEY_F7;
        case GLFW_KEY_F8:
            return GLVF_KEY_F8;
        case GLFW_KEY_F9:
            return GLVF_KEY_F9;
        case GLFW_KEY_F10:
            return GLVF_KEY_F10;
        case GLFW_KEY_F11:
            return GLVF_KEY_F11;
        case GLFW_KEY_F12:
            return GLVF_KEY_F12;
        case GLFW_KEY_F13:
            return GLVF_KEY_F13;
        case GLFW_KEY_F14:
            return GLVF_KEY_F14;
        case GLFW_KEY_F15:
            return GLVF_KEY_F15;
        case GLFW_KEY_F16:
            return GLVF_KEY_F16;
        case GLFW_KEY_F17:
            return GLVF_KEY_F17;
        case GLFW_KEY_F18:
            return GLVF_KEY_F18;
        case GLFW_KEY_F19:
            return GLVF_KEY_F19;
        case GLFW_KEY_F20:
            return GLVF_KEY_F20;
        case GLFW_KEY_F21:
            return GLVF_KEY_F21;
        case GLFW_KEY_F22:
            return GLVF_KEY_F22;
        case GLFW_KEY_F23:
            return GLVF_KEY_F23;
        case GLFW_KEY_F24:
            return GLVF_KEY_F24;
        case GLFW_KEY_F25:
            return GLVF_KEY_F25;
        case GLFW_KEY_KP_0:
            return GLVF_KEY_KEYPAD0;
        case GLFW_KEY_KP_1:
            return GLVF_KEY_KEYPAD1;
        case GLFW_KEY_KP_2:
            return GLVF_KEY_KEYPAD2;
        case GLFW_KEY_KP_3:
            return GLVF_KEY_KEYPAD3;
        case GLFW_KEY_KP_4:
            return GLVF_KEY_KEYPAD4;
        case GLFW_KEY_KP_5:
            return GLVF_KEY_KEYPAD5;
        case GLFW_KEY_KP_6:
            return GLVF_KEY_KEYPAD6;
        case GLFW_KEY_KP_7:
            return GLVF_KEY_KEYPAD7;
        case GLFW_KEY_KP_8:
            return GLVF_KEY_KEYPAD8;
        case GLFW_KEY_KP_9:
            return GLVF_KEY_KEYPAD9;
        case GLFW_KEY_KP_DECIMAL:
            return GLVF_KEY_KEYPAD_DECIMAL;
        case GLFW_KEY_KP_DIVIDE:
            return GLVF_KEY_KEYPAD_DIVIDE;
        case GLFW_KEY_KP_MULTIPLY:
            return GLVF_KEY_KEYPAD_MULTIPLY;
        case GLFW_KEY_KP_SUBTRACT:
            return GLVF_KEY_KEYPAD_SUBTRACT;
        case GLFW_KEY_KP_ADD:
            return GLVF_KEY_KEYPAD_ADD;
        case GLFW_KEY_KP_ENTER:
            return GLVF_KEY_KEYPAD_ENTER;
        case GLFW_KEY_KP_EQUAL:
            return GLVF_KEY_UNKNOWN; // TODO equals
        case GLFW_KEY_LEFT_SHIFT:
            return GLVF_KEY_SHIFT_LEFT;
        case GLFW_KEY_LEFT_CONTROL:
            return GLVF_KEY_L_CONTROL;
        case GLFW_KEY_LEFT_ALT:
            return GLVF_KEY_L_ALT;
        case GLFW_KEY_LEFT_SUPER:
            return GLVF_KEY_WIN_LEFT;
        case GLFW_KEY_RIGHT_SHIFT:
            return GLVF_KEY_SHIFT_RIGHT;
        case GLFW_KEY_RIGHT_CONTROL:
            return GLVF_KEY_R_CONTROL;
        case GLFW_KEY_RIGHT_ALT:
            return GLVF_KEY_R_ALT;
        case GLFW_KEY_RIGHT_SUPER:
            return GLVF_KEY_WIN_RIGHT;
        case GLFW_KEY_MENU:
            return GLVF_KEY_MENU;
    }
}
#endif